#!/bin/bash -f
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_1_2004.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_1_2005.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_1_2006.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_2_2000.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_2_2001.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_2_2002.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_2_2003.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_2_2004.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_2_2005.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_2_2006.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_5_1999.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_5_2000.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_5_2002.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_5_2005.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_7_2004.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_7_2005.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_11_2002.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_11_2003.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_11_2004.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_11_2005.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_13_2002.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_13_2003.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_14_2003.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_14_2004.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_14_2005.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_14_2006.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_17_2002.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_17_2003.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_18_2002.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_18_2003.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_18_2004.slurm
sbatch ./job_scripts/cal_scripts/soil_moisture_cal_18_2005.slurm
