#!/bin/bash -f
/bin/rm back_1.out
/bin/rm back_2.out
/bin/rm back_3.out
/bin/rm back_4.out
/bin/rm back_5.out
/bin/rm back_6.out
/bin/rm back_7.out
/bin/rm back_8.out
/bin/rm back_9.out
/bin/rm open_1.out
/bin/rm open_2.out
/bin/rm open_3.out
/bin/rm open_4.out
/bin/rm open_5.out
/bin/rm open_6.out
/bin/rm open_7.out
/bin/rm open_8.out
/bin/rm open_9.out
/bin/rm enks_1.out
/bin/rm enks_2.out
/bin/rm enks_3.out
/bin/rm enks_4.out
/bin/rm enks_5.out
/bin/rm enks_6.out
/bin/rm enks_7.out
/bin/rm enks_8.out
/bin/rm enks_9.out
