#!/bin/bash

#sbatch ./job_scripts/gpr_scripts/trainGPR_1_2004.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_1_2005.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_1_2006.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_2_2000.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_2_2001.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_2_2002.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_2_2003.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_2_2004.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_2_2005.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_2_2006.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_5_1999.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_5_2000.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_5_2002.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_5_2005.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_7_2004.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_7_2005.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_11_2002.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_11_2003.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_11_2004.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_11_2005.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_13_2002.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_13_2003.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_14_2003.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_14_2004.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_14_2005.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_14_2006.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_18_2002.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_18_2003.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_18_2004.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_18_2005.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_17_2002.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_17_2003.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2009.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2010.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2011.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2012.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2013.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2014.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2015.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2016.slurm
#sbatch ./job_scripts/gpr_scripts/trainGPR_21_2017.slurm
sbatch ./job_scripts/gpr_scripts/trainGPR_21_2018.slurm
